[build]
  command = ""
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["data/**"]

[[redirects]]
  from = "/api/words"
  to = "/.netlify/functions/words"
  status = 200